messaround:
		clear	
		g++ -Wall -Werror -pedantic --std=c++11 messaround.cpp -o messaround.out
		./messaround.out

hw: 
		clear
		g++ -Wall -Werror -pedantic -g --std=c++11 hw.cpp -o hw.out
		./hw.out

hw2: 
		clear
		g++ -Wall -Werror -pedantic -g --std=c++11 hw2.cpp -o hw2.out
		./hw2.out

clean:
	clear
	rm -vf *.out *.exe *.dSYM

